// <auto-generated />
using FormCreatorMVC.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FormCreatorMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190504151220_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FormCreatorMVC.DAL.Models.Forms", b =>
                {
                    b.Property<string>("ID");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("CreatedAt");

                    b.Property<int>("CreatorAge");

                    b.Property<string>("CreatorLastName");

                    b.Property<string>("CreatorName")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID", "CreatedBy");

                    b.ToTable("Forms");
                });
#pragma warning restore 612, 618
        }
    }
}
